services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456 
      POSTGRES_DB: mercadinho
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./BD:/docker-entrypoint-initdb.d
    ports:
      - "54320:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
 
volumes:
  pgdata: